// Generated by CoffeeScript 1.8.0
(function() {
  var Creep, _,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  _ = require('Score');

  module.exports = Creep = (function(_super) {
    __extends(Creep, _super);

    function Creep(creep) {
      var sources;
      this.creep = creep;
      if (this.creep.energy < creep.energyCapacity) {
        sources = creep.room.find(Game.SOURCES);
        creep.moveTo(sources[0]);
        creep.harvest(sources[0]);
      } else {
        creep.moveTo(Game.spawns.Spawn1);
        creep.transferEnergy(Game.spawns.Spawn1);
      }
    }

    Creep.test2 = function() {
      return this.test();
    };

    return Creep;

  })(_);

}).call(this);
