// Generated by CoffeeScript 1.8.0
(function() {
  var Score,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  module.exports = Score = (function(_super) {
    __extends(Score, _super);

    function Score() {
      return Score.__super__.constructor.apply(this, arguments);
    }

    Score.test = function() {
      return this;
    };

    return Score;

  })(require("lodash"));

}).call(this);
